project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  post-render:
    - "touch docs/.nojekyll"

website:
  title: "Nikhil Damodaran"
  navbar:
    left:
      - text: "Home"
        href: index.html

format:
  html:
    theme: cosmo
    toc: true
