---
title: "Fiscal Policy via Public Finance"
bibliography: /Users/ndamodaran/Library/CloudStorage/Dropbox/Nikhil/bibliography/References.bib
---

## Why this page?

This is the stuff that I have been reading before offering a course in Public Finance. The sepcific objective of this course is to not approach it from a macro perspective, but from a traditional public finance perspective. I want to cover the standard topics in public finance, but also want to cover the fiscal policy topics that are relevant for macroeconomics. This is a work in progress, and I will update it as I go along.

## What Fiscal Policy?

Fiscal policy has gone through popularity cycles based on discourse in academia. However, as many have argued (see Blinder), these cycles are more prominent in academic circles and less prominent in policy circles. Economic policy discussions have historically always included fiscal policy as a central theme, guiding such management throughout the broader arc of documented economic history. The last twenty years have seen a re-discussion of its place and a re-design of the economic thinking around fiscal policy with more evidence mounting towards its efficacy especially in times of limited maneuverability of monetary policy.

On this paper, I focus on the key aspects of fiscal policy, which are still contentious, need further empirical validation, and present an increasingly complicated fiscal ecosystem. This is also a reflection of the state and role of fiscal policy in the larger thinking in academic macroeconomics.

## The Original Proposition

The debate surrounding the role of government came about historically. Between the two world wars and immediately after it, there were two strong forces which dictated the economic revival. There was a part of discourse which urged a hands off approach for the government and believed in private unfettered entrepreneurship driven by incentives and liberal choices. At the backdrop of the world war where choices were limited and individuals were restricted, economies were constrained, this was a counter-movement to the global political order. On the other end of the spectrum was this realization that governments must lead the revival of economies with large public spending programs and greater interactions with markets in most economies. The extreme position was one where governments were the only method of resource allocation and economic prosperity. Hence there was a historical re-thinking of the role of government intervention in an economy at the same time there was a general shift in the way the world works.

## Market Faliures

Those who argued the general absence of government also conceded the need to facilitate government intervention in cases where market system collapses for some reason.

## Role of Sovereign

\`\`The operation of the public sector, as developed by the classical economists, is seen in the context of a natural order which calls for reliance on and non-interference with the market...The prince, therefore, is "discharged from any duty of superintending the industry of private people". But the system of natural liberty still needs the prince. It requires him to perform three duties, "duties of great importance indeed, but plain and intelligible to common understandings". These duties are, first, to protect society against invasion from abroad; second, to protect every member of society from the injustice of every other member; and third, to provide certain institutions and public works...''

## Normative vs Positive

A normative question is one concerned with how things should be done.

This is a positive question, one concerned with why things are the way they are.

## How economists think about fiscal policy

In 2000, a survey of 298 members of the American Economic Association (AEA) found that while 84 percent generally agreed with the statement "Fiscal policy has a significant stimulative impact on a less than fully employed economy", 71 percent also generally agreed with the statement "Management of the business cycle should be left to the Federal Reserve; activist fiscal policy should be avoided."

In 2011, a follow-up survey of 568 AEA members found that the previous consensus about the latter proposition had dissolved and was by then roughly evenly disputed.

## Can we categorize fiscal policy as expansionary or contractionary?

The idea is that since fiscal policy is linked to output i.e. proportional to output, we have an automatic increase and decrease of fiscal revenue and expenditure at least to the extent that they are proportional to output.

However, these definitions can be misleading because, even with no changes in spending or tax laws at all, cyclic fluctuations of the economy cause cyclic fluctuations of tax revenues and of some types of government spending, altering the deficit situation; these are not considered to be policy changes. Therefore, for purposes of the above definitions, "government spending" and "tax revenue" are normally replaced by "cyclically adjusted government spending" and "cyclically adjusted tax revenue". Thus, for example, a government budget that is balanced over the course of the business cycle is considered to represent a neutral and effective fiscal policy stance.

## Financing with Bonds/Debt and its International Implications

When governments fund a deficit with the issuing of government bonds, interest rates can increase across the market, because government borrowing creates higher demand for credit in the financial markets. This decreases aggregate demand for goods and services, either partially or entirely offsetting the direct expansionary impact of the deficit spending, thus diminishing or eliminating the achievement of the objective of a fiscal stimulus.

In the classical view, expansionary fiscal policy also decreases net exports, which has a mitigating effect on national output and income. When government borrowing increases interest rates it attracts foreign capital from foreign investors. This is because, all other things being equal, the bonds issued from a country executing expansionary fiscal policy now offer a higher rate of return. In other words, companies wanting to finance projects must compete with their government for capital so they offer higher rates of return. To purchase bonds originating from a certain country, foreign investors must obtain that country's currency. Therefore, when foreign capital flows into the country undergoing fiscal expansion, demand for that country's currency increases. The increased demand, in turn, causes the currency to appreciate, reducing the cost of imports and making exports from that country more expensive to foreigners. Consequently, exports decrease and imports increase, reducing demand from net exports.

## Some references

@Musgrave1985HPE @Christiano2000ER

@Cochrane2022JEP @Cochrane2021JEP

Great recent work by two different Bianchi's on fiscal policy.

@Bianchi2023QJE

@Bianchi2023JPE