---
title: International Trade Reading List
format: html
---

## Why this page?
This is a reading list mostly on classical trade theories, trade policy and some recent developments in the field within these subfields. Generally, these topics are less interesting to the journals so there needs to be a newer empirical or theoretical hook for work on these models to continue.

# Comparative Advantage

## Pedagogic

1.  Findlay, R. (1987). Comparative advantage. In The new Palgrave dictionary of economics (pp. 1-7). Palgrave Macmillan, London.

2.  Bernhofen, D. M., & Brown, J. C. (2018). Retrospectives: On the genius behind David Ricardo's 1817 formulation of comparative advantage. *Journal of Economic Perspectives*, *32*(4), 227-240.

## Theory

1.  Dornbusch, R., Fischer, S., & Samuelson, P. A. (1977). [Comparative advantage, trade, and payments in a Ricardian model with a continuum of goods.](https://www.jstor.org/stable/1828066) *The American Economic Review*, *67*(5), 823-839. The definitive many good version of Ricardian model which has become the textbook version of Ricardian model at higher levels.

2.  Costinot, A., Donaldson, D., Vogel, J., & Werning, I. (2015). Comparative advantage and optimal trade policy. *The Quarterly Journal of Economics*, *130*(2), 659-702. This is a very important paper. The idea is that while we have a reasonable understanding of comparative advantage, we do not have an understanding of what this model says about trade policy and intervention. This is an attempt at answering different set of questions using the model which posits comparative advantage. \* This is an interesting way of posing a question too. If we cannot contribute by asking old questions, ask new questions from the old model.

3.  Gaubert, C., & Itskhoki, O. (2021). Granular comparative advantage. *Journal of Political Economy*, *129*(3), 871-939. This is the most recent work using comparative advantage. This also could be the intersection of international trade (a conventional field) and industrial policy which specifically focuses on how to curb the market power of some large firms. They break down comparative advantage to an average firm behavior v. behavior generated by some large firms.

4.  Grossman, G. M., & Helpman, E. (1990). Comparative Advantage and Long-Run Growth. *The American Economic Review*, *80*(4), 796. Very well cited work.

5.  Bernard, A. B., Redding, S. J., & Schott, P. K. (2007). Comparative advantage and heterogeneous firms. *The Review of Economic Studies*, *74*(1), 31-66. Very well cited. The theory combines a two-country model with specialization based trade with heterogeneous firms.

6.  Clarida, R. H., & Findlay, R. (1992). Government, trade, and comparative advantage. *The American Economic Review*, *82*(2), 122-127. Intersection of comparative advantage and government intervention.

7.  Costinot, A. (2009). An elementary theory of comparative advantage. *Econometrica*, *77*(4), 1165-1192. Good extension of DFS.

8.  Deardorff, A. V. (1980). The general validity of the law of comparative advantage. *Journal of Political Economy*, *88*(5), 941-957.

9.  Deardorff, A. V. (2005). How robust is comparative advantage?. *Review of International Economics*, *13*(5), 1004-1016.

10. Costinot, A. (2009). On the origins of comparative advantage. *Journal of International Economics*, *77*(2), 255-264.

11. Neary, J. P. (2007). Cross-border mergers as instruments of comparative advantage. *The Review of Economic Studies*, *74*(4), 1229-1257.

12. Keesing, D. B. (1966). Labor skills and comparative advantage. *The American Economic Review*, *56*(1/2), 249-258.

13. Redding, S. (1999). Dynamic comparative advantage and the welfare effects of trade. *Oxford economic papers*, *51*(1), 15-39.

14. Matsuyama, K. (1992). Agricultural productivity, comparative advantage, and economic growth. *Journal of economic theory*, *58*(2), 317-334.

## Empirics

1.  D. M. Bernhofen and J. C. Brown. A direct test of the theory of comparative advantage: the case of Japan. *Journal of Political Economy*, 112(1):48–67, 2004.

2.  A. Costinot and D. Donaldson. Ricardo’s theory of comparative advantage: old idea, new evidence. *American Economic Review Papers and Proceedings*, 102(3):453–458, 2012.

3.  Levchenko, A. A., & Zhang, J. (2016). The evolution of comparative advantage: Measurement and welfare implications. *Journal of Monetary Economics*, *78*, 96-111. A sectoral take on specialization and comparative advantage. Cross country regressions but at the sectoral level. Thinking about doing this work, if it could be done, seems silly at this stage. Especially because at the time this work was published, cross country convergence regressions were discarded and empirical work would have been looked down upon.

4.  Golub, S. S. and Hsieh, C.-T. (2000). Classical ricardian theory of comparative advantage revisited. *Review of international economics*, 8(2):221–234.

5.  Chor, D. (2010). Unpacking sources of comparative advantage: A quantitative approach. *Journal of International Economics*, *82*(2), 152-167.

6.  Hummels, D. and Levinsohn, J. (1993). Product differentiation as a source of comparative advantage? *The American Economic Review Papers and Proceedings*, 83(2):445–449.

7.  Hoen, A. R., & Oosterhaven, J. (2006). On the measurement of comparative advantage. *The Annals of Regional Science*, *40*(3), 677-691.

## Comparative Advantage Applied Elsewhere

1.  Boehm, J., Dhingra, S., & Morrow, J. (2022). The comparative advantage of firms. *Journal of Political Economy*, *130*(12), 3025-3100. Interesting piece of evidence on Indian firms production structure. The idea is that if firms have readily available inputs, then they tend to specialize and produce in the sector which has fewer input frictions.

2.  Davis, D. R., & Dingel, J. I. (2020). The comparative advantage of cities. *Journal of International Economics*, *123*, 103291. The idea is that of underlying labor specialization which causes some cities to specialize in some products. The intersection of labor and trade is very nice.

3.  Hunt, S. D., & Morgan, R. M. (1995). The comparative advantage theory of competition. *Journal of marketing*, *59*(2), 1-15. This piece is even more cited than the benchmark comparative advantage work by DFS. It is applying comparative advantage as a concept to marketing and explaining the monopoly power of firms. 5K citations and counting.

4.  Suri, T. (2011). Selection and comparative advantage in technology adoption. *Econometrica*, *79*(1), 159-209. This is the concept adapted to technology adoption by farmers. The data applied to an econometric model is what makes this work worthy of econometrica. It is a sharp neat application.

5.  Nunn, N., & Trefler, D. (2014). Domestic institutions as a source of comparative advantage. *Handbook of international economics*, *4*, 263-315. This paper examines how domestic institutions can be a source of comparative advantage. So rather than pinning comparative advantage to technology or labor productivity, this talks about institutions such as what Adam Smith mentions when he talks about institutions supporting free market to function and trade to occur.

6.  Liu, X., Mattoo, A., Wang, Z., & Wei, S. J. (2020). Services development and comparative advantage in manufacturing. *Journal of Development Economics*, *144*, 102438.

7.  Do, Q. T., Levchenko, A. A., & Raddatz, C. (2016). Comparative advantage, international trade, and fertility. *Journal of Development economics*, *119*, 48-66.

8.  Ju, J., & Wei, S. J. (2011). When is quality of financial system a source of comparative advantage?. *Journal of International Economics*, *84*(2), 178-187.

# Exchange Rates

## Purchasing Power Parity

The idea here is that purchasing power parity is a long run phenomenon with a convergence to this anchor in the very long run. Rogoff gives the 3-5 year half life result. Since the convergence is so slow, people are less interested in this theoretical long term benchmark but rather interested in short run exchange rate movements.

A leading reason for this lack of interest is: rather than viewing exchange rate parity as a result of equalization of goods prices, it started being viewed as a result of financial interaction, at least in the short run. This implies that things such as monetary policy differences across countries, capital flows, international exchange rate futures trade became more important to the determination of exchange rate.

A second reason for the disconnect is that firms price discriminate across countries which implies that exchange rate pass-through is incomplete and local currency pricing matters. Hence if by construction firms are treating different international markets differently, then the difference in exchange rate will reflect the difference in import/domestic consumption composition.

A third reason for the disconnect is that a large part of domestic prices is explained by non-tradables such as rents, local services such as haircuts, restaurants etc. Hence, when the CPI has more non-tradables, there is no reason to assume PPP equalization. This is connected to the idea extended by Balassa-Samuelson when they argued that countries will differ in price levels because of differences in productivity across tradeables which permeate into non-tradables.

1.  Rogoff, K. (1996). The purchasing power parity puzzle. *Journal of Economic literature*, *34*(2), 647-668.
2.  Balassa, B. (1964). The purchasing-power parity doctrine: a reappraisal. *Journal of political Economy*, *72*(6), 584-596.
3.  Pinkovskiy, M., & Sala-i-Martin, X. (2020). Shining a light on purchasing power parities. *American Economic Journal: Macroeconomics*, *12*(4), 71-108.
4.  Taylor, A. M., & Taylor, M. P. (2002). The purchasing power parity debate. *Journal of economic perspectives*, *18*(4), 135-158.
5.  Dornbusch, R. (1987). Purchasing power parity. In *The new Palgrave dictionary of economics* (pp. 1-16). Palgrave Macmillan, London.
6.  Vo, H. L., & Vo, D. H. (2023). The purchasing power parity and exchange‐rate economics half a century on. *Journal of Economic Surveys*, *37*(2), 446-479.
7.  Frenkel, J. A. (1978). Purchasing power parity: Doctrinal perspective and evidence from the 1920s. *Journal of International Economics*, *8*(2), 169-191.

# Tariffs

## Empirical Results

1.  Suwanprasert, W. (2026). Exchange rate responses to the 2025 US Liberation Day tariff announcement. *International Economics*, 100691.

# Interesting Papers

1.  Hayek, F. V. (1989). The pretence of knowledge (Nobel Lecture). *American Economic Review*, *79*(6), 3-7.
2.  Hayek, F. A. (1945). The Use of Knowledge in Society. *The American Economic Review*, *35*(4), 519-530. - massive citation and potentially nobel causing work which i have no clue about.
